# Exploratory Data Analysis of Global Life Expectancy and Healthy Life Expectancy

## Problem Statement

Life expectancy and healthy life expectancy vary considerably across countries, genders, and geographic regions. Understanding these variations can help identify important patterns in global health and differences in the number of years people are expected to live in good health.

This project aims to explore global life expectancy and healthy life expectancy data from 2000 to 2021 to identify trends and relationships across countries. The analysis focuses on factors such as life expectancy, healthy life expectancy, gender differences, the gap between life expectancy and healthy life expectancy, and variations across WHO geographic regions.

The findings from this exploratory analysis can provide useful insights into global health patterns, differences in longevity and healthy years of life, and the factors reflected in variations between countries and regions.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Load raw datasets
life_raw = pd.read_csv(r"90E2E48_ALL_LATEST.csv")
healthy_raw = pd.read_csv(r"C64284D_ALL_LATEST.csv")

In [5]:
#viewing raw datasets
life_raw.head(5)

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,DIM_SEX,AMOUNT_N,AMOUNT_NL,AMOUNT_NU
0,90E2E48WHOSIS_000001,WHOSIS_000001,90E2E48,WHOSIS_000001,2000,YEAR,688,COUNTRY,PUBLISHED,Life expectancy (at birth),Serbia,FEMALE,74.334559,74.254810,74.526428
1,90E2E48WHOSIS_000001,WHOSIS_000001,90E2E48,WHOSIS_000001,2000,YEAR,690,COUNTRY,PUBLISHED,Life expectancy (at birth),Seychelles,FEMALE,76.455919,76.227948,76.712025
2,90E2E48WHOSIS_000001,WHOSIS_000001,90E2E48,WHOSIS_000001,2000,YEAR,694,COUNTRY,PUBLISHED,Life expectancy (at birth),Sierra Leone,FEMALE,51.577824,50.603903,52.778978
3,90E2E48WHOSIS_000001,WHOSIS_000001,90E2E48,WHOSIS_000001,2000,YEAR,702,COUNTRY,PUBLISHED,Life expectancy (at birth),Singapore,FEMALE,80.774170,80.751426,80.876353
4,90E2E48WHOSIS_000001,WHOSIS_000001,90E2E48,WHOSIS_000001,2000,YEAR,703,COUNTRY,PUBLISHED,Life expectancy (at birth),Slovakia,FEMALE,77.405510,77.356596,77.519091

In [6]:
healthy_raw.head(5)

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,DIM_SEX,AMOUNT_N,AMOUNT_NL,AMOUNT_NU
0,C64284DWHOSIS_000002,WHOSIS_000002,C64284D,WHOSIS_000002,2000,YEAR,728,COUNTRY,PUBLISHED,Healthy life expectancy (at birth),South Sudan,FEMALE,45.530197,44.327494,46.667307
1,C64284DWHOSIS_000002,WHOSIS_000002,C64284D,WHOSIS_000002,2000,YEAR,729,COUNTRY,PUBLISHED,Healthy life expectancy (at birth),Sudan,FEMALE,54.288355,53.330383,55.318639
2,C64284DWHOSIS_000002,WHOSIS_000002,C64284D,WHOSIS_000002,2000,YEAR,740,COUNTRY,PUBLISHED,Healthy life expectancy (at birth),Suriname,FEMALE,63.007150,62.212438,63.939485
3,C64284DWHOSIS_000002,WHOSIS_000002,C64284D,WHOSIS_000002,2000,YEAR,748,COUNTRY,PUBLISHED,Healthy life expectancy (at birth),Eswatini,FEMALE,42.615748,40.978123,44.290711
4,C64284DWHOSIS_000002,WHOSIS_000002,C64284D,WHOSIS_000002,2000,YEAR,752,COUNTRY,PUBLISHED,Healthy life expectancy (at birth),Sweden,FEMALE,69.983014,69.353504,70.855616

In [7]:
# Creating copies
life = life_raw.copy()
healthy = healthy_raw.copy()

In [8]:
# checking shape 
print("Life expectancy raw:", life_raw.shape)
print("Healthy life expectancy raw:", healthy_raw.shape)

print("Life expectancy working copy:", life.shape)
print("Healthy life expectancy working copy:", healthy.shape)

Life expectancy raw: (12936, 15)
Healthy life expectancy raw: (12936, 15)
Life expectancy working copy: (12936, 15)
Healthy life expectancy working copy: (12936, 15)

In [9]:
#checking columns
print("Life expectancy columns:")
print(life.columns.tolist())

print("\nHealthy life expectancy columns:")
print(healthy.columns.tolist())

print("\nLife expectancy sample:")
print(life.head())

print("\nHealthy life expectancy sample:")
print(healthy.head())

Life expectancy columns:
['IND_ID', 'IND_CODE', 'IND_UUID', 'IND_PER_CODE', 'DIM_TIME', 'DIM_TIME_TYPE', 'DIM_GEO_CODE_M49', 'DIM_GEO_CODE_TYPE', 'DIM_PUBLISH_STATE_CODE', 'IND_NAME', 'GEO_NAME_SHORT', 'DIM_SEX', 'AMOUNT_N', 'AMOUNT_NL', 'AMOUNT_NU']

Healthy life expectancy columns:
['IND_ID', 'IND_CODE', 'IND_UUID', 'IND_PER_CODE', 'DIM_TIME', 'DIM_TIME_TYPE', 'DIM_GEO_CODE_M49', 'DIM_GEO_CODE_TYPE', 'DIM_PUBLISH_STATE_CODE', 'IND_NAME', 'GEO_NAME_SHORT', 'DIM_SEX', 'AMOUNT_N', 'AMOUNT_NL', 'AMOUNT_NU']

Life expectancy sample:
                 IND_ID       IND_CODE IND_UUID   IND_PER_CODE  DIM_TIME  \
0  90E2E48WHOSIS_000001  WHOSIS_000001  90E2E48  WHOSIS_000001      2000
1  90E2E48WHOSIS_000001  WHOSIS_000001  90E2E48  WHOSIS_000001      2000
2  90E2E48WHOSIS_000001  WHOSIS_000001  90E2E48  WHOSIS_000001      2000
3  90E2E48WHOSIS_000001  WHOSIS_000001  90E2E48  WHOSIS_000001      2000
4  90E2E48WHOSIS_000001  WHOSIS_000001  90E2E48  WHOSIS_000001      2000

  DIM_TIME_TYPE  DIM_GEO_CODE_M49 DIM_GEO_CODE_TYPE DIM_PUBLISH_STATE_CODE  \
0          YEAR               688           COUNTRY              PUBLISHED
1          YEAR               690           COUNTRY              PUBLISHED
2          YEAR               694           COUNTRY              PUBLISHED
3          YEAR               702           COUNTRY              PUBLISHED
4          YEAR               703           COUNTRY              PUBLISHED

                     IND_NAME GEO_NAME_SHORT DIM_SEX   AMOUNT_N  AMOUNT_NL  \
0  Life expectancy (at birth)         Serbia  FEMALE  74.334559  74.254810
1  Life expectancy (at birth)     Seychelles  FEMALE  76.455919  76.227948
2  Life expectancy (at birth)   Sierra Leone  FEMALE  51.577824  50.603903
3  Life expectancy (at birth)      Singapore  FEMALE  80.774170  80.751426
4  Life expectancy (at birth)       Slovakia  FEMALE  77.405510  77.356596

   AMOUNT_NU
0  74.526428
1  76.712025
2  52.778978
3  80.876353
4  77.519091

Healthy life expectancy sample:
                 IND_ID       IND_CODE IND_UUID   IND_PER_CODE  DIM_TIME  \
0  C64284DWHOSIS_000002  WHOSIS_000002  C64284D  WHOSIS_000002      2000
1  C64284DWHOSIS_000002  WHOSIS_000002  C64284D  WHOSIS_000002      2000
2  C64284DWHOSIS_000002  WHOSIS_000002  C64284D  WHOSIS_000002      2000
3  C64284DWHOSIS_000002  WHOSIS_000002  C64284D  WHOSIS_000002      2000
4  C64284DWHOSIS_000002  WHOSIS_000002  C64284D  WHOSIS_000002      2000

  DIM_TIME_TYPE  DIM_GEO_CODE_M49 DIM_GEO_CODE_TYPE DIM_PUBLISH_STATE_CODE  \
0          YEAR               728           COUNTRY              PUBLISHED
1          YEAR               729           COUNTRY              PUBLISHED
2          YEAR               740           COUNTRY              PUBLISHED
3          YEAR               748           COUNTRY              PUBLISHED
4          YEAR               752           COUNTRY              PUBLISHED

                             IND_NAME GEO_NAME_SHORT DIM_SEX   AMOUNT_N  \
0  Healthy life expectancy (at birth)    South Sudan  FEMALE  45.530197
1  Healthy life expectancy (at birth)          Sudan  FEMALE  54.288355
2  Healthy life expectancy (at birth)       Suriname  FEMALE  63.007150
3  Healthy life expectancy (at birth)       Eswatini  FEMALE  42.615748
4  Healthy life expectancy (at birth)         Sweden  FEMALE  69.983014

   AMOUNT_NL  AMOUNT_NU
0  44.327494  46.667307
1  53.330383  55.318639
2  62.212438  63.939485
3  40.978123  44.290711
4  69.353504  70.855616

In [10]:
# Checking data types

print("Life expectancy data types:")
print(life.dtypes)

print("\nHealthy life expectancy data types:")
print(healthy.dtypes)

Life expectancy data types:
IND_ID                     object
IND_CODE                   object
IND_UUID                   object
IND_PER_CODE               object
DIM_TIME                    int64
DIM_TIME_TYPE              object
DIM_GEO_CODE_M49            int64
DIM_GEO_CODE_TYPE          object
DIM_PUBLISH_STATE_CODE     object
IND_NAME                   object
GEO_NAME_SHORT             object
DIM_SEX                    object
AMOUNT_N                  float64
AMOUNT_NL                 float64
AMOUNT_NU                 float64
dtype: object

Healthy life expectancy data types:
IND_ID                     object
IND_CODE                   object
IND_UUID                   object
IND_PER_CODE               object
DIM_TIME                    int64
DIM_TIME_TYPE              object
DIM_GEO_CODE_M49            int64
DIM_GEO_CODE_TYPE          object
DIM_PUBLISH_STATE_CODE     object
IND_NAME                   object
GEO_NAME_SHORT             object
DIM_SEX                    object
AMOUNT_N                  float64
AMOUNT_NL                 float64
AMOUNT_NU                 float64
dtype: object