# Exploratory Analysis

This notebook contains the statistical analysis, distributions, groupby calculations, percentages, relationships, and findings for Q1–Q10.

## Q1. How has life expectancy changed across countries from 2000 to 2021?

In [40]:
#Average life expectancy by year

life = (
    df[
        (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
        (df["DIM_SEX"] == "TOTAL")
    ]
    .groupby("DIM_TIME")["AMOUNT_N_life"]
    .mean()
)

print("Average life expectancy by year:")
life

Average life expectancy by year:

DIM_TIME
2000    66.915183
2001    67.249249
2002    67.480139
2003    67.750674
2004    68.087770
2005    68.437038
2006    68.886803
2007    69.248200
2008    69.602174
2009    69.998406
2010    70.248527
2011    70.669331
2012    70.982093
2013    71.292523
2014    71.445156
2015    71.625279
2016    71.888790
2017    72.121260
2018    72.357077
2019    72.559107
2020    71.993142
2021    71.226627
Name: AMOUNT_N_life, dtype: float64

In [41]:
# Country-level change in life expectancy from 2000 to 2021

life_change = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
    (df["DIM_SEX"] == "TOTAL") &
    (df["DIM_TIME"].isin([2000, 2021]))
][
    ["GEO_NAME_SHORT", "DIM_TIME", "AMOUNT_N_life"]
]

life_change_pivot = life_change.pivot(
    index="GEO_NAME_SHORT",
    columns="DIM_TIME",
    values="AMOUNT_N_life"
)

life_change_pivot["Change"] = (
    life_change_pivot[2021] -
    life_change_pivot[2000]
)

# Largest increase
life_change_pivot.sort_values(
    "Change", ascending=False
).head(10)

DIM_TIME                          2000       2021     Change
GEO_NAME_SHORT
Rwanda                       46.894472  67.542139  20.647666
Burundi                      44.360918  64.006950  19.646032
Malawi                       44.641263  62.486526  17.845263
Uganda                       48.890040  65.985779  17.095739
Ethiopia                     50.787605  67.839091  17.051486
Zambia                       44.527139  60.968843  16.441703
Botswana                     47.163836  61.231192  14.067356
United Republic of Tanzania  52.792273  66.810148  14.017875
Angola                       49.367744  62.131135  12.763391
Zimbabwe                     45.745290  58.481022  12.735732

In [43]:
# Calculating the change between 2000 and 2021

change = life.iloc[-1] - life.iloc[0]

print("Life expectancy in 2000:", round(life.iloc[0], 2))
print("Life expectancy in 2021:", round(life.iloc[-1], 2))
print("Overall change:", round(change, 2), "years")

Life expectancy in 2000: 66.92
Life expectancy in 2021: 71.23
Overall change: 4.31 years

## Q2. How has healthy life expectancy changed across countries from 2000 to 2021?

In [45]:
#Average healthy life expectancy by year

healthy = (
    df[
        (df["DIM_GEO_CODE_TYPE_healthy"] == "COUNTRY") &
        (df["DIM_SEX"] == "TOTAL")
    ]
    .groupby("DIM_TIME")["AMOUNT_N_healthy"]
    .mean()
)

healthy

DIM_TIME
2000    58.295244
2001    58.572726
2002    58.777567
2003    59.019939
2004    59.300877
2005    59.598120
2006    59.968007
2007    60.277283
2008    60.579521
2009    60.915774
2010    61.128853
2011    61.476931
2012    61.744413
2013    62.008001
2014    62.142941
2015    62.302398
2016    62.517614
2017    62.710786
2018    62.901888
2019    63.067081
2020    62.534314
2021    61.839734
Name: AMOUNT_N_healthy, dtype: float64

In [46]:
# Country-level change in healthy life expectancy from 2000 to 2021

healthy_change = df[
    (df["DIM_GEO_CODE_TYPE_healthy"] == "COUNTRY") &
    (df["DIM_SEX"] == "TOTAL") &
    (df["DIM_TIME"].isin([2000, 2021]))
][
    ["GEO_NAME_SHORT", "DIM_TIME", "AMOUNT_N_healthy"]
]

healthy_change_pivot = healthy_change.pivot(
    index="GEO_NAME_SHORT",
    columns="DIM_TIME",
    values="AMOUNT_N_healthy"
)

healthy_change_pivot["Change"] = (
    healthy_change_pivot[2021] -
    healthy_change_pivot[2000]
)

healthy_change_pivot

DIM_TIME                                 2000       2021     Change
GEO_NAME_SHORT
Afghanistan                         46.027950  50.446244   4.418293
Albania                             64.477408  66.687955   2.210548
Algeria                             62.936140  65.548192   2.612052
Angola                              42.847181  53.761870  10.914689
Antigua and Barbuda                 64.891452  66.522822   1.631370
...                                       ...        ...        ...
Venezuela (Bolivarian Republic of)  64.377406  62.046159  -2.331247
Viet Nam                            63.737653  65.351125   1.613471
Yemen                               54.151354  56.463678   2.312324
Zambia                              38.891980  52.970094  14.078115
Zimbabwe                            40.531216  51.248912  10.717696

[183 rows x 3 columns]

In [48]:
# Calculate the change between 2000 and 2021

change_healthy = healthy.iloc[-1] - healthy.iloc[0]

print("Healthy life expectancy in 2000:", round(healthy.iloc[0], 2))
print("Healthy life expectancy in 2021:", round(healthy.iloc[-1], 2))
print("Overall change:", round(change_healthy, 2), "years")

Healthy life expectancy in 2000: 58.3
Healthy life expectancy in 2021: 61.84
Overall change: 3.54 years

## Q3. Which countries had the highest and lowest life expectancy in the latest available year?

In [50]:
#Life expectancy by country in 2021 
life_country = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
    (df["DIM_SEX"] == "TOTAL") &
    (df["DIM_TIME"] == 2021)
][
    ["GEO_NAME_SHORT", "AMOUNT_N_life"]
].sort_values(
    "AMOUNT_N_life",
    ascending=False
)

life_country

                 GEO_NAME_SHORT  AMOUNT_N_life
12769                     Japan      84.460672
12480                 Singapore      83.857090
12774         Republic of Korea      83.799823
12493               Switzerland      83.327958
12071                 Australia      83.101839
...                         ...            ...
12621                Mozambique      57.662027
12491                  Eswatini      54.592670
12484                   Somalia      53.951439
11944  Central African Republic      52.307728
12779                   Lesotho      51.479075

[183 rows x 2 columns]

In [51]:
#highest
print("Top 10 countries:")
life_country.head(10)

Top 10 countries:

          GEO_NAME_SHORT  AMOUNT_N_life
12769              Japan      84.460672
12480          Singapore      83.857090
12774  Republic of Korea      83.799823
12493        Switzerland      83.327958
12071          Australia      83.101839
12631             Norway      82.881999
12784         Luxembourg      82.780286
12492             Sweden      82.664909
12487              Spain      82.662673
12934            Iceland      82.577667

In [52]:
#lowest
print("Bottom 10 countries:")
life_country.tail(10)

Bottom 10 countries:

                 GEO_NAME_SHORT  AMOUNT_N_life
12064               Afghanistan      59.126902
11946                      Chad      59.085814
12641             Guinea-Bissau      58.628018
12488               South Sudan      58.573539
12486                  Zimbabwe      58.481022
12621                Mozambique      57.662027
12491                  Eswatini      54.592670
12484                   Somalia      53.951439
11944  Central African Republic      52.307728
12779                   Lesotho      51.479075

## Q4. Which countries had the highest and lowest healthy life expectancy in the latest available year?

In [55]:
#Healthy life expectancy by country in 2021

healthy_country = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
    (df["DIM_SEX"] == "TOTAL") &
    (df["DIM_TIME"] == 2021)
][
    ["GEO_NAME_SHORT", "AMOUNT_N_healthy"]
].sort_values(
    "AMOUNT_N_healthy",
    ascending=False
)

healthy_country

                 GEO_NAME_SHORT  AMOUNT_N_healthy
12480                 Singapore         73.646950
12769                     Japan         73.395184
12774         Republic of Korea         72.450586
12934                   Iceland         71.370486
12784                Luxembourg         71.234411
...                         ...               ...
12621                Mozambique         49.715911
12491                  Eswatini         47.467403
12484                   Somalia         47.423385
11944  Central African Republic         45.432893
12779                   Lesotho         44.634333

[183 rows x 2 columns]

In [56]:
# highest 
print("Top 10 countries:")
healthy_country.head(10)

Top 10 countries:

          GEO_NAME_SHORT  AMOUNT_N_healthy
12480          Singapore         73.646950
12769              Japan         73.395184
12774  Republic of Korea         72.450586
12934            Iceland         71.370486
12784         Luxembourg         71.234411
12631             Norway         71.155305
12493        Switzerland         71.149159
12492             Sweden         71.118320
12487              Spain         71.107015
12765             Israel         70.757525

In [57]:
#lowest
print("Bottom 10 countries")
healthy_country.tail(10)

Bottom 10 countries

                 GEO_NAME_SHORT  AMOUNT_N_healthy
11946                      Chad         51.515060
12641             Guinea-Bissau         51.450365
12486                  Zimbabwe         51.248912
12488               South Sudan         50.530017
12064               Afghanistan         50.446244
12621                Mozambique         49.715911
12491                  Eswatini         47.467403
12484                   Somalia         47.423385
11944  Central African Republic         45.432893
12779                   Lesotho         44.634333

## Q5. How does life expectancy differ between males and females across countries?

In [60]:
#Compare life expectancy between males and females across countries in 2021

life_sex = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
    (df["DIM_SEX"].isin(["MALE", "FEMALE"])) &
    (df["DIM_TIME"] == 2021)
][
    ["GEO_NAME_SHORT", "DIM_SEX", "AMOUNT_N_life"]
]

life_sex

              GEO_NAME_SHORT DIM_SEX  AMOUNT_N_life
3306  Bosnia and Herzegovina  FEMALE      77.197966
3307                Botswana  FEMALE      63.179313
3308                  Brazil  FEMALE      75.847278
3309                  Belize  FEMALE      75.440193
3310         Solomon Islands  FEMALE      67.334360
...                      ...     ...            ...
8619                   Haiti    MALE      61.699673
8620                Honduras    MALE      67.437589
8621                 Hungary    MALE      70.944228
8622                 Iceland    MALE      81.329741
8623                   India    MALE      65.771929

[366 rows x 3 columns]

In [61]:
# Reshape the data to compare male and female life expectancy for each country

life_sex_pivot = life_sex.pivot(
    index="GEO_NAME_SHORT",
    columns="DIM_SEX",
    values="AMOUNT_N_life"
)

life_sex_pivot

DIM_SEX                                FEMALE       MALE
GEO_NAME_SHORT
Afghanistan                         60.986038  57.403782
Albania                             78.612388  74.360824
Algeria                             76.638748  75.506435
Angola                              64.255839  60.007463
Antigua and Barbuda                 78.417267  75.206337
...                                       ...        ...
Venezuela (Bolivarian Republic of)  75.949540  66.855861
Viet Nam                            77.957301  69.725241
Yemen                               68.568192  63.088526
Zambia                              63.109315  58.720946
Zimbabwe                            60.533378  56.194609

[183 rows x 2 columns]

In [62]:
# Calculate the difference between female and male life expectancy for each country

life_sex_pivot["Gap"] = (
    life_sex_pivot["FEMALE"] -
    life_sex_pivot["MALE"]
)

life_sex_pivot

DIM_SEX                                FEMALE       MALE       Gap
GEO_NAME_SHORT
Afghanistan                         60.986038  57.403782  3.582256
Albania                             78.612388  74.360824  4.251565
Algeria                             76.638748  75.506435  1.132313
Angola                              64.255839  60.007463  4.248375
Antigua and Barbuda                 78.417267  75.206337  3.210929
...                                       ...        ...       ...
Venezuela (Bolivarian Republic of)  75.949540  66.855861  9.093680
Viet Nam                            77.957301  69.725241  8.232060
Yemen                               68.568192  63.088526  5.479666
Zambia                              63.109315  58.720946  4.388369
Zimbabwe                            60.533378  56.194609  4.338770

[183 rows x 3 columns]

In [63]:
# Calculate the average life expectancy for males and females across all countries

sex_average = life_sex.groupby(
    "DIM_SEX"
)["AMOUNT_N_life"].mean()

sex_average

DIM_SEX
FEMALE    73.686134
MALE      68.849704
Name: AMOUNT_N_life, dtype: float64

In [64]:
# Calculate the average female-male life expectancy gap across countries

life_sex_pivot["Gap"].mean()

4.836430225464481

## Q6 — How does healthy life expectancy differ between males and females across countries?

In [67]:
#Healthy life expectancy comparison between males and females in 2021

healthy_sex = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
    (df["DIM_SEX"].isin(["MALE", "FEMALE"])) &
    (df["DIM_TIME"] == 2021)
][
    ["GEO_NAME_SHORT", "DIM_SEX", "AMOUNT_N_healthy"]
]

healthy_sex

              GEO_NAME_SHORT DIM_SEX  AMOUNT_N_healthy
3306  Bosnia and Herzegovina  FEMALE         66.108201
3307                Botswana  FEMALE         53.899727
3308                  Brazil  FEMALE         63.405779
3309                  Belize  FEMALE         64.700965
3310         Solomon Islands  FEMALE         58.543344
...                      ...     ...               ...
8619                   Haiti    MALE         54.327681
8620                Honduras    MALE         59.588393
8621                 Hungary    MALE         62.936926
8622                 Iceland    MALE         71.423559
8623                   India    MALE         57.972339

[366 rows x 3 columns]

In [68]:
# Average healthy life expectancy by sex

healthy_sex_average = healthy_sex.groupby("DIM_SEX")["AMOUNT_N_healthy"].mean()

print("Average healthy life expectancy by sex:")
healthy_sex_average

Average healthy life expectancy by sex:

DIM_SEX
FEMALE    62.866121
MALE      60.829891
Name: AMOUNT_N_healthy, dtype: float64

In [69]:
# Calculate female-male healthy life expectancy gap

healthy_sex_pivot = healthy_sex.pivot(
    index="GEO_NAME_SHORT",
    columns="DIM_SEX",
    values="AMOUNT_N_healthy"
)

healthy_sex_pivot["Gap"] = (
    healthy_sex_pivot["FEMALE"] -
    healthy_sex_pivot["MALE"]
)

print("Average female-male healthy life expectancy gap:",
      healthy_sex_pivot["Gap"].mean())

Average female-male healthy life expectancy gap: 2.03623092273224

## Q7 — What is the gap between life expectancy and healthy life expectancy across countries?

In [72]:
#Gap between life expectancy and healthy life expectancy in 2021

health_gap = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
    (df["DIM_SEX"] == "TOTAL") &
    (df["DIM_TIME"] == 2021)
][
    ["GEO_NAME_SHORT", "AMOUNT_N_life", "AMOUNT_N_healthy", "Health_Gap"]
].sort_values(
    "Health_Gap",
    ascending=False
)

health_gap

                 GEO_NAME_SHORT  AMOUNT_N_life  AMOUNT_N_healthy  Health_Gap
12071                 Australia      83.101839         70.606358   12.495480
12335  United States of America      76.373681         63.914957   12.458724
12627               New Zealand      82.201492         69.983217   12.218275
12493               Switzerland      83.327958         71.149159   12.178798
12917                    France      81.922742         70.083459   11.839282
...                         ...            ...               ...         ...
12641             Guinea-Bissau      58.628018         51.450365    7.177653
12491                  Eswatini      54.592670         47.467403    7.125266
11944  Central African Republic      52.307728         45.432893    6.874835
12779                   Lesotho      51.479075         44.634333    6.844742
12484                   Somalia      53.951439         47.423385    6.528054

[183 rows x 4 columns]

In [73]:
# Average gap between life expectancy and healthy life expectancy

average_health_gap = health_gap["Health_Gap"].mean()

print("Average health gap:",
      average_health_gap)

Average health gap: 9.386893050710382

In [74]:
# Minimum and maximum health gap

print("Largest health gap:",
      health_gap["Health_Gap"].max())

print("Smallest health gap:",
      health_gap["Health_Gap"].min())

Largest health gap: 12.495480319999999
Smallest health gap: 6.528054140000002

## Q8 — Which countries have the largest and smallest gap between life expectancy and healthy life expectancy?

In [77]:
#Countries with the largest and smallest health gaps in 2021

top_10_gap = health_gap.head(10)
bottom_10_gap = health_gap.tail(10)

plot_data = pd.concat([
    top_10_gap,
    bottom_10_gap
]).sort_values("Health_Gap")

plot_data[["GEO_NAME_SHORT", "Health_Gap"]]

                 GEO_NAME_SHORT  Health_Gap
12484                   Somalia    6.528054
12779                   Lesotho    6.844742
11944  Central African Republic    6.874835
12491                  Eswatini    7.125266
12641             Guinea-Bissau    7.177653
12925                  Kiribati    7.223579
12486                  Zimbabwe    7.232110
12629                     Niger    7.360790
11934           Solomon Islands    7.425280
12623                   Namibia    7.536983
12766                     Italy   11.632819
12640                  Portugal   11.660340
12078                   Belgium   11.711284
12631                    Norway   11.726693
11942                    Canada   11.799166
12917                    France   11.839282
12493               Switzerland   12.178798
12627               New Zealand   12.218275
12335  United States of America   12.458724
12071                 Australia   12.495480

## Q9 — How does life expectancy vary across different geographic regions?

In [80]:
#Life expectancy across WHO regions in 2021

region_life = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "WHOREGION") &
    (df["DIM_SEX"] == "TOTAL") &
    (df["DIM_TIME"] == 2021)
][
    ["GEO_NAME_SHORT", "AMOUNT_N_life"]
]

region_life

              GEO_NAME_SHORT  AMOUNT_N_life
12200                 Europe      76.287289
12201  Eastern Mediterranean      68.487436
12202        Western Pacific      77.418143
12347                 Africa      63.552439
12348               Americas      74.112688
12349        South-East Asia      68.366830

## Q10 — What is the relationship between life expectancy and healthy life expectancy across countries?

In [83]:
#Relationship between life expectancy and healthy life expectancy in 2021

relationship = df[
    (df["DIM_GEO_CODE_TYPE_life"] == "COUNTRY") &
    (df["DIM_SEX"] == "TOTAL") &
    (df["DIM_TIME"] == 2021)
][
    ["GEO_NAME_SHORT", "AMOUNT_N_life", "AMOUNT_N_healthy"]
]

relationship

                         GEO_NAME_SHORT  AMOUNT_N_life  AMOUNT_N_healthy
11929  Bolivia (Plurinational State of)      65.410625         57.425399
11930            Bosnia and Herzegovina      74.849445         64.985820
11931                          Botswana      61.231192         53.103672
11932                            Brazil      72.388407         61.826535
11933                            Belize      73.320553         63.824716
...                                 ...            ...               ...
12931                             Haiti      62.456386         53.936195
12932                          Honduras      68.963093         60.046481
12933                           Hungary      74.395470         64.838792
12934                           Iceland      82.577667         71.370486
12935                             India      67.307806         58.146748

[183 rows x 3 columns]

In [85]:
# Calculate correlation

correlation = relationship["AMOUNT_N_life"].corr(
    relationship["AMOUNT_N_healthy"]
)

print("Correlation:", correlation)

Correlation: 0.9951845506028506